### PR TITLE
Fix #65 Error on closing outline when computer is running slow

### LINKED ISSUE #65: Error on closing outline when computer is running slow
Hi,
  I have been facing following issue when my PC is running bit slow and I quickly open and close outline.

```
Error executing lua callback: ...ite/pack/lazy/opt/outline.nvim/lua/outline/highlight.lua:12: Invalid 'buffer': Expected Lua number
stack traceback:
	[C]: in function 'nvim_buf_clear_namespace'
	...ite/pack/lazy/opt/outline.nvim/lua/outline/highlight.lua:12: in function 'clear_all_ns'
	...vim/site/pack/lazy/opt/outline.nvim/lua/outline/view.lua:96: in function 'clear_all_ns'
	.../site/pack/lazy/opt/outline.nvim/lua/outline/sidebar.lua:875: in function 'build_outline'
	.../site/pack/lazy/opt/outline.nvim/lua/outline/sidebar.lua:293: in function '_update_lines'
	.../site/pack/lazy/opt/outline.nvim/lua/outline/sidebar.lua:707: in function '_highlight_current_item'
	.../site/pack/lazy/opt/outline.nvim/lua/outline/sidebar.lua:237: in function <.../site/pack/lazy/opt/outline.nvim/lua/outline/sidebar.lua:236>
```

my configuration is as follows: ( I have been using it for a long time and ported it from symbols.nvim)
```
{
  "hedyhli/outline.nvim",
  config = function()
    require("outline").setup {
      highlight_hovered_item = true,
      show_guides = true,
      auto_preview = false,
      position = 'right',
      relative_width = true,
      width = 34,
      auto_close = false,
      show_numbers = false,
      show_relative_numbers = true,
      show_symbol_details = false,
      preview_bg_highlight = 'Pmenu',
      autofold_depth = nil,
      auto_unfold_hover = true,
      fold_markers = { '', '' },
      wrap = false,
      symbol_folding = {
        autofold_depth = 1,
        auto_unfold = {
          hovered = true,
        },
      },
      outline_window = {
        show_cursorline = true,
        hide_cursor = true,
        jump_highlight_duration = 1,
      },
      --outline_items = {
      --  show_symbol_lineno = true,
      --},
      keymaps = { -- These keymaps can be a string or a table for multiple keys
        close = { "<Esc>", "q" },
        goto_location = "<Cr>",
        focus_location = "o",
        hover_symbol = "<C-space>",
        toggle_preview = "K",
        rename_symbol = "r",
        code_actions = "a",
        fold = "h",
        unfold = "l",
        fold_all = "W",
        unfold_all = "E",
        fold_reset = "R",
      },

      lsp_blacklist = {},
      symbol_blacklist = {},
      symbols = {
        File = { icon = "", hl = "@text.uri" },
        Module = { icon = "󰕳", hl = "@namespace" },
        Namespace = { icon = "", hl = "@namespace" },
        Package = { icon = "󰏓", hl = "@namespace" },
        Class = { icon = "𝓒", hl = "@type" },
        Method = { icon = "ƒ", hl = "@method" },
        Property = { icon = "", hl = "@method" },
        Field = { icon = "󰘤", hl = "@field" },
        Constructor = { icon = "", hl = "@constructor" },
        Enum = { icon = "ℰ", hl = "@type" },
        Interface = { icon = "", hl = "@type" },
        Function = { icon = "", hl = "@function" },
        Variable = { icon = "", hl = "@constant" },
        Constant = { icon = "", hl = "@constant" },
        String = { icon = "𝓐", hl = "@string" },
        Number = { icon = "#", hl = "@number" },
        Boolean = { icon = "⊨", hl = "@boolean" },
        Array = { icon = "", hl = "@constant" },
        Object = { icon = "⦿", hl = "@type" },
        Key = { icon = "🔐", hl = "@type" },
        Null = { icon = "NULL", hl = "@type" },
        EnumMember = { icon = "", hl = "@field" },
        Struct = { icon = "𝓢", hl = "@type" },
        Event = { icon = "🗲", hl = "@type" },
        Operator = { icon = "+", hl = "@operator" },
        TypeParameter = { icon = "𝙏", hl = "@parameter" },
        Component = { icon = "󰹫", hl = "@function" },
        Fragment = { icon = "󱀤", hl = "@constant" },
      }
    }
  end,
}
```

I have a patch as well which apparently fixes this issue. I will create the PR along with this issue. 
So:
- If I made a mistake in config then please do let me know and thank you for taking the time to go through my lengthy config and finding the issue 😺 
- If the config seems ok, then please do review the PR and by all means do suggest if you think there is a better way to fix the issue. 

Thank you.

### PR DESCRIPTION
**Pull request by m-abubakar**
This PR resolves issue on closing outline when computer is running slow.

### CODE REVIEW

File: lua/outline/highlight.lua [hunk 1]
```diff
@@ -9,13 +9,17 @@ local M = {
 ---Clear all highlights in buffer
 ---@param bufnr integer
 function M.clear_all_ns(bufnr)
-  vim.api.nvim_buf_clear_namespace(bufnr, -1, 0, -1)
+  if vim.api.nvim_buf_is_valid(bufnr) then
+    pcall(function() vim.api.nvim_buf_clear_namespace(bufnr, -1, 0, -1) end)
```
Comment (hedyhli) [inline lua/outline/highlight.lua:13]: Is this `pcall` still needed after we've already checked the `bufnr` is valid? You haven't added the pcall anywhere else. Do you still encounter this issue if we unwrap the `clear_namespace` call from pcall here?

**Review by hedyhli — COMMENTED** [review]
Thanks for your PR.

I'm not sure why you're getting this issue, possibly a race condition. Your fix looks reasonable and for now I'm not able to troubleshoot/reproduce it so I'm fine with merging it as-is so long as it does fix the issue, just one comment.

File: lua/outline/highlight.lua (hunk 1 above)
Comment (m-abubakar) [reply lua/outline/highlight.lua:13]: Hi,
  Yes, as you correctly assumed it is due to race conditions. `pcall` here is needed. I also found another issue with the `Sidebar:update_cursor_pos`. Apparently when we quickly close the outline window right after pressing enter on the selected symbol, the `Sidebar:destroy` is called which sets self.view to nil and then in the `Sidebar:update_cursor_pos` we get an error due to this. 

I think to tackle all these issue we should implement some sort of state machine which only destroys the objects when we are done with all the callbacks. What are your thoughts on this ?

Comment (m-abubakar) [reply lua/outline/highlight.lua:13]: FYI, to reproduce the issue: 
When the PC is under some load, 
   - Quickly open the symbol sidebar select a symbol (which is known to be bit lower in the file) 
   - Press enter on the selected symbol and quickly close the outline sidebar.

I see a lot of errors popping up when I do this. When this happens, outline auto-commands are left in some inconsistent state. Therefore on every cursor move similar errors keeps popping up. I then have to re-open the neovim to fix it.

**Comment by moljac024** [comment]
I still experience this error from time to time and the only fix is to quit and re-open neovim. That sucks as it makes you lose all your editor state and takes you out of flow.

Are there some blockers to merging this?

**Comment by lyokha** [comment]
This patch:

```diff
diff --git a/lua/outline/sidebar.lua b/lua/outline/sidebar.lua
index e0a5f8d..5ebe1ad 100644
--- a/lua/outline/sidebar.lua
+++ b/lua/outline/sidebar.lua
@@ -347,7 +347,9 @@ function Sidebar:__refresh()
   self.provider, self.provider_info = providers.find_provider()
   if self.provider then
     self.provider.request_symbols(function(res)
-      self:refresh_handler(res)
+      if self.view:is_open() then
+        self:refresh_handler(res)
+      end
     end, nil, self.provider_info)
     return
   end
```

fixes the error on fast open/close of the outline window. When I did fast switches before the patch, I always got the error on LSP-based outline bars, now they have gone.

The idea of the patch is to check if the outline window is still open in the LSP response callback which is the patched anonymous function passed in `self.provider.request_symbols()`.

**Comment by hedyhli** [comment]
Alright, I'll look into triaging this some time tomorrow.

**Comment by lyokha** [comment]
There is another (not related) fix regarding callbacks:

```diff
diff --git a/lua/outline/sidebar.lua b/lua/outline/sidebar.lua
index e0a5f8d..cccf930 100644
--- a/lua/outline/sidebar.lua
+++ b/lua/outline/sidebar.lua
@@ -318,9 +318,14 @@ function Sidebar:refresh_handler(response)
     return
   end
 
+  local curbuf = vim.api.nvim_get_current_buf()
+  if curbuf == self.view.buf then
+    return
+  end
+
   local newbuf = self:refresh_setup()
 
-  local items = parser.parse(response, vim.api.nvim_get_current_buf())
+  local items = parser.parse(response, curbuf)
   self:_merge_items(items)
 
   local update_cursor = newbuf or cfg.o.outline_items.auto_set_cursor
```

Getting current buffer in the refresh callback must be taken cautiously because the refresh could have been initialized in the code window and finished in the sidebar (if cursor moved there when the callback was in progress). I got error

```
E5108: Error executing lua: .../share/nvim/plugged/outline.nvim/lua/outline/sidebar.lua:400: Cursor position outside buffer                                                           
stack traceback:                                                                                                                                                                              
        [C]: in function 'nvim_win_set_cursor'                                                                                                                                                
        .../share/nvim/plugged/outline.nvim/lua/outline/sidebar.lua:400: in function '__goto_location'                                                                                        
        .../share/nvim/plugged/outline.nvim/lua/outline/sidebar.lua:422: in function <.../share/nvim/plugged/outline.nvim/lua/outline/sidebar.lua:421>                                        
        .../share/nvim/plugged/outline.nvim/lua/outline/sidebar.lua:125: in function <.../share/nvim/plugged/outline.nvim/lua/outline/sidebar.lua:125>
```

due to this missing check on fast open/close/jump to and from the outline sidebar with `OutlineRefresh` called from `timer_start()` every 500ms (I used that to let outline automatically redraw in some time when a quicker provider, say ctags from an external plugin, hijacked the outline bar). Debugging this, I found that the error occurred only when the buffer happened to appear the outline sidebar itself. After putting the check the error ceased.

**Comment by hedyhli** [comment]
Thanks @lyokha, I've applied these in main.

**Comment by lyokha** [comment]
Thanks!
